### ISSUE TITLE
Xutils.h - XSizeHints is wrong size

### ISSUE THREAD

**Issue by PhilipWitte** [D-Programming-Deimos/libX11#11]
Currently the structure looks like:

````D
struct XSizeHints {
    c_long flags;
    int x, y;
    int width, height;
    int min_width, min_height;
    int max_width, max_height;
    int width_inc, height_inc;
    struct min_aspect {
        int x;
        int y;
    };
    struct max_aspect {
        int x;
        int y;
    };
    int base_width, base_height;
    int win_gravity;
}
````
Which, when tested is 64 bytes on 64bit Linux (DMD). The original C structure in Xutils.h however is 80 bytes on the same machine (GCC). That's because min_aspect/max_aspect are only type declarations. The D structure should look like:

````D
struct XSizeHints {
    c_long flags;
    int x, y;
    int width, height;
    int min_width, min_height;
    int max_width, max_height;
    int width_inc, height_inc;
    
    struct aspect {
        int x, y;
    }
    
    aspect min_aspect, max_aspect;
    
    int base_width, base_height;
    int win_gravity;
}
````

There may be similar issues with other sub-struct types in Deimos/libX11, but I haven't searched for them yet.

**Comment by CyberShadow** [comment]
I understand this has been fixed in https://github.com/D-Programming-Deimos/libX11/pull/12.
