### ISSUE TITLE
Multiple "extern(C)" function  declarations named Data

### ISSUE THREAD

**Issue by tyrolite** [D-Programming-Deimos/libX11#17]
I get this error:

deimos/X11/Xlibint.d(895): Error: Function type does not match 
previously declared function with the same mangled name: Data

while building with the latest ldc2 as default compiler. Building with dmd 2.063.2 works fine.

see more in this thread: http://forum.dlang.org/thread/edllepkxhfrwvitvwvtw@forum.dlang.org

**Comment by CyberShadow** [comment]
https://github.com/D-Programming-Deimos/libX11/pull/40

**Comment by schveiguy** [comment]
Merged #40
