### ISSUE TITLE
Usefulness XI* macros

### ISSUE THREAD

**Issue by Temtaime** [D-Programming-Deimos/libX11#24]
XISetMask
XIClearMask
XIMaskIsSet
XIMaskLen

These macros are strange templates with string argument. I thing they should be simple functions for example:

void XISetMask(ubyte[] mask, uint event) { 
mask[event >> 3] |= 1 << (event & 7); 
}

**Comment by CyberShadow** [comment]
> These macros are strange templates with string argument.

That's mildly put. As presently declared, they are completely useless. E.g. `XISetMask` tries to modify a string template parameter, which is wrong on more than one level (modifying a string, which is immutable, and modifying a template parameter, which by definition cannot be modified).

**Comment by CyberShadow** [comment]
Fixed in #42.
