### ISSUE TITLE
Xproto type conflicts

### ISSUE THREAD

**Issue by growlercab** [D-Programming-Deimos/libX11#32]
In Xproto.d some types from X.d and Xatom.d are redefined using alias which causes conflicts.

This works in Xproto.h because the alias is a #define and the types are all #undef at the end of the include file.

The following snippet is from Xproto.d, which lists the conflicting types.

``` D
/* For the purpose of the structure definitions in this file,
we must redefine the following types in terms of Xmd.h's types, which may
include bit fields.  All of these are #undef'd at the end of this file,
restoring the definitions in X.h.  */

alias CARD32    Window;
alias CARD32    Drawable;
alias CARD32    Font;
alias CARD32    Pixmap;
alias CARD32    Cursor;
alias CARD32    Colormap;
alias CARD32    GContext;
alias CARD32    Atom;
alias CARD32    VisualID;
alias CARD32    Time;
alias CARD8     KeyCode;
alias CARD32    KeySym;
```

**Comment by CyberShadow** [comment]
@growlercab I've updated your PR and resubmitted it along with another fix in https://github.com/D-Programming-Deimos/libX11/pull/43.

**Comment by growlercab** [comment]
@CyberShadow thanks for updating this PR and #43.

**Comment by CyberShadow** [comment]
I believe this was fixed when https://github.com/D-Programming-Deimos/libX11/pull/46 was merged.
