### ISSUE TITLE
Building with GDC gives 'unrecognized option' error.

### ISSUE THREAD

**Issue by IanWizard** [D-Programming-Deimos/libX11#4]
Using gdc-4.6 from Ubuntu 11.10 repos.

$ make DC=gdc
Makefile:159: warning: overriding commands for target `install'
Makefile:156: warning: ignoring old commands for target `install'
gdc -O2 -fdeprecated -m64 -Xlinker-ldl -m64  -c deimos/X11/Xlib.d -obuild/deimos/X11/Xlib.o
gdc: error: unrecognized option ‘-Xlinker-ldl’
make: *** [build/deimos/X11/Xlib.o] Error 1

**Comment by CyberShadow** [comment]
Since no one seems to be using or maintaining the makefiles (I proposed to remove them in https://github.com/D-Programming-Deimos/libX11/pull/39), I'm going to close this. Dub and rdmd should work great with this project. Let me know if this should be reopened.
