### ISSUE TITLE
Adding it to any project means it'll no longer build on Windows

### ISSUE THREAD

**Issue by ZILtoid1991** [D-Programming-Deimos/libX11#52]
Adding `platform="linux"` to the dub file does not make it skip on non-Linux targets, and will ask for "x11.lib".

**Comment by CyberShadow** [comment]
Well, this package does host the bindings to a C library. Removing the dependency in `dub.json` will just likely make it fail to link.

I think we would need to look at a specific use case to figure out what to do with it.

**Comment by CyberShadow** [comment]
Writing a Windows application that talks to an X server isn't that weird. There are X servers that run on Windows, or you might want to do this e.g. if you were writing a clipboard utility that synchronizes your clipboard between Windows and Linux. So, I don't think this is our problem to solve.
